app:
  secret_key: "your-secret-key-here"
  debug: true

# Multi-index configuration - users must select a prefecture
indexes:
  tokyo:
    dir: "data/tokyo/index"
    name: "Tokyo"
  osaka:
    dir: "data/osaka/index"
    name: "Osaka"
  kochi:
    dir: "data/kochi/index"
    name: "Kochi"