app:
  secret_key: "your-secret-key-here"
  debug: true

# Tokenizer configuration
tokenizer:
  type: janome  # Options: 'janome', 'mecab', or null for auto-detect (tries MeCab first, falls back to Janome)

# Multi-index configuration - users must select a prefecture
indexes:
  tokyo:
    dir: "data/indexes/tokyo"
    name: "Tokyo"
  osaka:
    dir: "data/indexes/osaka"
    name: "Osaka"
  kochi:
    dir: "data/indexes/kochi"
    name: "Kochi"