# Configuration for JSON folder tokenization with DataFrame merging
input:
  csv_file: null
  json_folder: "data/test_json_companies"
  dataframe_file: "data/test_company_info.csv"
  
processing:
  batch_size: 500
  max_content_length: 10000
  extra_columns:
    - cust_status
  
output:
  output_dir: null                  # Auto-generate: data/test_json_companies/tokenized
  clear_output: false
  
tokenizer:
  included_pos: 
    - "名詞"
    - "動詞"
    - "形容詞"
    - "副詞"
  min_word_length: 2
  stop_words_filtered: true